name: "configure-git-author"
description: "Configure the git identity"
inputs:
  username:
    description: "Git username"
    required: true
  email:
    description: "Email"
    required: true
  global:
    description: "Global scope"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        GIT_GLOBAL_OPTION=''
        if [ ${INPUTS_GLOBAL} = true ] ; then
           GIT_GLOBAL_OPTION='--global'
        fi
        git config $GIT_GLOBAL_OPTION user.name ${INPUTS_USERNAME}
        git config $GIT_GLOBAL_OPTION user.email ${INPUTS_EMAIL}
      env:
        INPUTS_GLOBAL: ${{ inputs.global }}
        INPUTS_USERNAME: ${{ inputs.username }}
        INPUTS_EMAIL: ${{ inputs.email }}
