name: 'Sonar Scanner'
description: 'Run Sonar Scanner to load JaCoCo report on SonarCloud'
inputs:
  sonar-token:
    description: 'SonarCloud token'
    required: true
  aggregate-report-path:
    description: 'Path of the aggregated JaCoCo report'
    required: true
  project-key:
    description: 'SonarCloud project key'
    required: true
  sonar-host-url:
    description: 'SonarCloud host url'
    required: false
    default: 'https://sonarcloud.io'
  sonar-organization:
    description: 'SonarCloud organization'
    required: false
    default: 'alfresco'


runs:
  using: composite
  steps:
    - name: Load JaCoCo report on SonarCloud
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        INPUTS_SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
        INPUTS_SONAR_ORGANIZATION: ${{ inputs.sonar-organization }}
        INPUTS_PROJECT_KEY: ${{ inputs.project-key }}
        INPUTS_AGGREGATE_REPORT_PATH: ${{ inputs.aggregate-report-path }}
      shell: bash
      run: |
        mvn sonar:sonar -Dsonar.host.url=${INPUTS_SONAR_HOST_URL} -Dsonar.organization=${INPUTS_SONAR_ORGANIZATION} -Dsonar.projectKey=${INPUTS_PROJECT_KEY} -Dsonar.coverage.jacoco.xmlReportPaths=${INPUTS_AGGREGATE_REPORT_PATH}
