---
name: Helm Plugin install
description: >
  Install an helm plugin from provided url
inputs:
  plugin_url:
    description: URL where to get the plugin from
    required: true
  plugin_version:
    description: version of the helm-unittest plugin to install
    required: false
    default: latest
runs:
  using: composite
  steps:
    - name: Install Helm plugin ${{ inputs.plugin_url }}
      shell: bash
      run: |
        set -e
        [ ${INPUTS_PLUGIN_VERSION} != 'latest' ] && \
        VER="--version ${INPUTS_PLUGIN_VERSION}"
        helm plugin install ${INPUTS_PLUGIN_URL} $VER
      env:
        INPUTS_PLUGIN_VERSION: ${{ inputs.plugin_version }}
        INPUTS_PLUGIN_URL: ${{ inputs.plugin_url }}
