name: "Github Download File"
description: "Download a file from another repository"
inputs:
  token:
    description: "GitHub Access Token"
    required: true
  repository:
    description: "The owner and repository name from which the file should be downloaded. For example, octocat/Hello-World."
    required: true
  file-path:
    description: "Path to the file you want to download"
    required: true
  target:
    description: "Where and with what name to save the file"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Download file"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUTS_REPOSITORY: ${{ inputs.repository }}
        INPUTS_FILE_PATH: ${{ inputs.file-path }}
        INPUTS_TARGET: ${{ inputs.target }}
      run: |
        export API_URL=https://api.github.com/repos/${INPUTS_REPOSITORY}/contents/${INPUTS_FILE_PATH}
        gh api $API_URL -H "Accept: application/vnd.github.raw" >> ${INPUTS_TARGET}
